KnowledgeHubProtal/Controllers/ArticlesController.cs
using KnowledgeHubProtal.Models.DataAccess;
using KnowledgeHubProtal.Models.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KnowledgeHubProtal.Controllers
{
    public class ArticlesController : Controller
    {
        // use DI
        ICategoryRepository cRepo;// = new CategoryRepository();
        KHPDbContext db;// = new KHPDbContext();

        public ArticlesController(ICategoryRepository repo, KHPDbContext db)
        {
            this.cRepo = repo;
            this.db = db;
        }


        public IActionResult Index() // list-display the data
        {
            var approvedArticles = from a in db.Articles
                                   where a.IsApproved == true
                                   select a;
            return View(approvedArticles.ToList());
        }

        [Authorize]
        [HttpGet]
        public IActionResult Submit()
        {
            //return View with category list
            // fetch the categories

            var categories = cRepo.GetAll();
            ViewBag.Categories = categories;
            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Submit(Article article)
        {
            // server side validation

            article.DateSubmited = DateTime.Now;
            article.Author = User.Identity.Name;
            //article.Author = "Unknown";
            article.IsApproved = false;

            //if (!ModelState.IsValid)
            //{
            //    var categories = cRepo.GetAll();
            //    ViewBag.Categories = categories;
            //    return View();
            //}
            db.Articles.Add(article);
            db.SaveChanges();

            TempData["Message"] = $"Article {article.Title} is sumitted successfully";

            return RedirectToAction("Submit");



        }
        [Authorize(Roles = "admin")]
        public IActionResult Review()
        {
            // fetch all new unapproved articles and return to view
            var unapprovedArticles = from a in db.Articles.Include(a => a.Category)
                                     where a.IsApproved == false
                                     select a;
            return View(unapprovedArticles);
        }
        [Authorize(Roles = "admin")]
        public IActionResult Approve(List<int> articlesid)
        {
            //TODO - make it efficient
            var allArticles = db.Articles;
            foreach (var article in allArticles)
            {
                foreach (var id in articlesid)
                {
                    if (article.ArticleID == id)
                    {
                        article.IsApproved = true;
                    }
                }
            }
            db.SaveChanges();
            return RedirectToAction("Review");
        }
        [Authorize(Roles = "admin")]
        public IActionResult Reject(List<int> articlesid)
        {
            //TODO - make it efficient
            var allArticles = db.Articles;
            foreach (var article in allArticles)
            {
                foreach (var id in articlesid)
                {
                    if (article.ArticleID == id)
                    {
                        db.Articles.Remove(article);
                    }
                }
            }
            db.SaveChanges();
            return RedirectToAction("Review");
        }

    }
}

KnowledgeHubProtal/Controllers/CategoriesController.cs
using KnowledgeHubProtal.Models.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace KnowledgeHubProtal.Controllers
{
    [Authorize(Roles = "admin")]
    public class CategoriesController : Controller
    {
        //CategoryRepository repo = new CategoryRepository();

        ICategoryRepository repo;

        // DI
        public CategoriesController(ICategoryRepository repo)
        {
            this.repo = repo;
        }



        //[AllowAnonymous]
        //.../Categories/Index
        public IActionResult Index(string term)
        {
            List<Category> categories = null;
            if (term.IsNullOrEmpty())
            {
                categories = repo.GetAll();
            }
            else
            {
                categories = repo.GetByName(term);
            }

            return View(categories);

            // return list of categories

        }

        // .../Categories/Create
        [HttpGet]
        public IActionResult Create()
        {
            // return a view for collecting category info
            return View();
        }
        // .../Categories/Create
        [HttpPost]
        public IActionResult Create(Category c)
        {
            // validation - Client Side - Server Side
            if (!ModelState.IsValid)
            {
                // return view to collect valid data
                return View();
            }


            // save
            //Category c = new Category { CategoryName = categoryname, CategoryDescription = categorydescription };
            repo.Create(c);

            string msg = $"Category {c.CategoryName} successfully created.";
            TempData["Message"] = msg;
            //ViewData["Message"] = msg;
            //ViewBag.Message = msg;
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            // return a view for editing category info
            // get the category by id
            var categoryToEdit = repo.GetById(id);
            return View(categoryToEdit);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            // validation - Client Side - Server Side
            if (!ModelState.IsValid)
            {
                // return view to collect valid data
                return View();
            }


            // save
            //Category c = new Category { CategoryName = categoryname, CategoryDescription = categorydescription };
            repo.Update(category);

            string msg = $"Category {category.CategoryName} successfully modified.";
            TempData["Message"] = msg;
            //ViewData["Message"] = msg;
            //ViewBag.Message = msg;
            return RedirectToAction("Index");
        }
    }

}

KnowledgeHubProtal/Controllers/UsersManagementController.cs
using KnowledgeHubProtal.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace KnowledgeHubProtal.Controllers
{
    public class UsersManagementController : Controller
    {

        ApplicationDbContext adb;
        UserManager<IdentityUser> userManager;

        // DI
        public UsersManagementController(ApplicationDbContext adb, UserManager<IdentityUser> manager)
        {
            this.adb = adb;
            this.userManager = manager;
        }

        public IActionResult Index()
        {

            // display all registerd user
            //var allUsers = adb.Users.ToList();

            var allUsers = userManager.Users.ToList();

            return View(allUsers);
        }
    }
}

KnowledgeHubProtal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Knowledge Hub Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KnowledgeHubProtal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Knowledge Hub Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Manage Categories</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Submit">Submit Article</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Review">Review Articles</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UsersManagement" asp-action="Index">Users</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">Browse Articles</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Knowledge Hub Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

KnowledgeHubProtal/Views/Shared/_WelcomePartialView.cshtml
@{ Layout = null;}
<div class="text-center">
    <h1 class="display-1">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>